version: '3.1'
services:
  redis:
    container_name: "ktu-redis"
    image: redis:5.0
    container_name: ktu-redis
    ports:
      - 6379:6379
  mongo:
    container_name: "ktu-mongodb"
    ports:
      - 27017:27017
    image: mongo:latest
  app:
    container_name: ktu-app
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - mongo
    command: ["npm", "run", "dev"]
